Finished samd upload details, bug fixes

diff --git a/multi-upload b/multi-upload
--- a/multi-upload
+++ b/multi-upload
@@ -30,16 +30,28 @@ trap "kill 0" EXIT
 
 ############### Define functions ###############
 help_txt(){
-    echo "usage: upload.sh [board_type] [project_file.ino]"
+echo -e "
+Multi-Upload (multi-upload).
+
+Usage:
+   multi-upload [flags...]
+
+Available Flags:
+   Project          -p <path>     Path to project folder.
+   IDE location     -i <path>     Path to Arduino IDE (.app).
+   Device RegEx     -d <regex>    RegEx string to select upload devices. (IE: /dev/cu*usb*)
+   Board Identifier -b <ident>    Board type identifier. (IE: arduino:avr:uno)
+   Manager URL add  -j <URL>      Adds <URL> to the board manager JSON list.
+   Sequential mode  -s            Uploads sequentially instead of in parallel.
+   Retry enable     -r            Enables single retry upon upload failures.
+   Cache enable     -c            Enables caching compile files.
+   Arduino-CLI      -l            Use arduino-cli to compile and upload.
+   Help dialog      -h            Display help and exit.
+"
 }
 
-# --pref "build.path=$build_path"
-# compile(){
-#     arduino-cli compile --fqbn "$1" $2 
-#     exit $?
-# }
 
-
+# Upload in parallel (Print to file)
 upload(){
     if [ "$USE_CLI" = false ]; then
         if [ "$CACHE" = false ]; then
@@ -47,26 +59,37 @@ upload(){
         else
             "$IDE_PATH/Contents/MacOS/Arduino" --board "$1" --port $3 --pref "build.path=$build_path" --upload "$2" 2> /tmp/multi-upload-out-$4
         fi
-        exit $?
     else
         if [[ "$1" == *"samd"* ]]; then
             echo "Detected SAMD"
             echo "Sending bootloader wakeup"
-            stty -f "$3" 1200
+            stty -f "$3" 1200 2> /dev/null
             sleep 1
             if [ ${PIPESTATUS[0]} -ne 0 ]; then
                 echo "Failed to touch serial port! ($3)"
                 exit 1
             fi
             eval $BOSSAC -i -d --port="\"$3\"" -U true -i -e -w -v "\"$BUILD_RES\"" -R
-            exit $?
         else
             arduino-cli upload -p "$3" --fqbn "$1" "$2" 2> /tmp/multi-upload-out-$4
         fi
-        exit $?
+    fi
+    if [ $? -ne 0 ]; then
+        if [ "$RETRY" = true ]; then
+            if [ "$5" = true ]; then
+                upload "$1" "$2" "$3" "$4" false
+            else
+                exit 1
+            fi
+        else
+            exit 1
+        fi
+    else
+        exit 0
     fi
 }
 
+# Upload sequentially (Print to console)
 upload_nofile(){
     echo "UPLOAD NF"
     if [ "$USE_CLI" = false ]; then
@@ -137,10 +160,12 @@ while getopts ":srhclb:p:i:d:j:" opt; do
       ;;
     \? )
       echo "Invalid option: $OPTARG" 1>&2
+      help_txt
       exit 1
       ;;
     : )
       echo "Invalid option: $OPTARG requires an argument" 1>&2
+      help_txt
       exit 1
       ;;
   esac
@@ -157,7 +182,7 @@ if [ "$USE_CLI" = false ]; then
     IFS='/' read -ra A_PATH <<< "${PROJECT%/}"
     printf -v PROJECT '%s/%s.ino' "${PROJECT%/}" "${A_PATH[${#A_PATH[@]}-1]}"
 else
-    CACHE=false
+    CACHE=true
 fi
 
 # if ! [ -f "$PROJECT" ]; then
@@ -241,9 +266,9 @@ if [ "$USE_CLI" = true ]; then
     # Turns out compiling slows the whole thing dowm more than it helps
     echo -e "\033[0;92mCompiling project...\033[0m"
     arduino-cli compile --fqbn "$BOARD" "$PROJECT" 2>&1 | awk '$0="\033[0m|\033[0;91m "$0'
+    echo $?
     if [ $? -ne 0 ]; then
-        echo -e "\033[0m→ \033[1;91mFAILED\033[0m"
-        echo -e "Compile with IDE or check log (/tmp/multi-upload-out-verify), retry"
+        echo -e "\033[0m→ \033[1;91mFAILED - Errors exist\033[0m"
         exit 1
     else
         BUILD_RES="$PROJECT"
@@ -251,15 +276,13 @@ if [ "$USE_CLI" = true ]; then
         PROJECT_NAME="${A_PATH[${#A_PATH[@]}-1]}"
         BOARD_DOT=$(echo "$BOARD" | tr ":" ".")
         printf -v BUILD_RES '%s/%s.%s.bin' "${PROJECT%/}" "$PROJECT_NAME" "$BOARD_DOT"
-        # if [ ! -f "$BUILD_RES" ]; then
-        #     printf -v BUILD_RES '%s/%s.%s.hex' "${PROJECT%/}" "$PROJECT_NAME" "$BOARD_DOT"
-        #     if [ ! -f "$BUILD_RES" ]; then
-        #         echo "Failed to locate resulting binary! ($BUILD_RES Not Found)"
-        #         exit 1
-        #     fi
-        # fi
         echo -e "\033[0m→ \033[0;92mSUCCESS\033[0m"
     fi
+fi
+
+if [ ${#array[@]} -eq 0 ]; then
+    echo "No devices meeting criteria, exit!"
+    exit 0
 fi
 
 # Init some variables
@@ -315,7 +338,7 @@ do
         echo ""
     else
         # Run an upload and set to background process with log file
-        upload "$BOARD" "$PROJECT" "$i" "$counter" 1> /dev/null &
+        upload "$BOARD" "$PROJECT" "$i" "$counter" true 1> /dev/null &
     fi
     # Append the log file to an array
     log_files+=("/tmp/multi-upload-out-$counter")
